kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "runtimeclass-controller.serviceAccountName" . }}
  labels:
    {{- include "runtimeclass-controller.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]