kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-web-view.serviceAccountName" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs: [list, get]
- nonResourceURLs:
  - '*'
  verbs: [list, get]