kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-web-view.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-web-view.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-web-view.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}