{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "coroot-node-agent.fullname" . }}
  labels:
    {{- include "coroot-node-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "coroot-node-agent.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: http
{{- end }}


