apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-diff-logger.fullname" . }}
  labels:
    {{- include "kubernetes-diff-logger.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  - batch
  resources:
  - daemonsets
  - deployments
  - statefulsets
  - cronjobs
  verbs:
  - list
  - watch