apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "parca.fullname" . }}
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  allowedHostPaths:
  - pathPrefix: /proc
  - pathPrefix: /sys
  - pathPrefix: /
  - pathPrefix: /lib
  - pathPrefix: /etc
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 7071
    min: 7071
  privileged: true
  readOnlyRootFilesystem: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  - hostPath