apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: {{ include "parca.fullname" . }}-agent
  namespace: parca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "parca.fullname" . }}-agent
subjects:
- kind: ServiceAccount
  name: {{ include "parca.fullname" . }}-agent