apiVersion: v1
kind: Service
metadata:
  name: {{ include "parca.fullname" . }}-server
  labels:
    {{- include "parca.labels.server" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 7070
      protocol: TCP
      name: http
  selector:
    {{- include "parca.selectorLabels.server" . | nindent 4 }}