apiVersion: v1
kind: Service
metadata:
  name: {{ include "parca.fullname" . }}
  labels:
    {{- include "parca.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.server.type }}
  ports:
    - port: {{ .Values.service.server.port }}
      targetPort: 7070
      protocol: TCP
      name: http
  selector:
    {{- include "parca.selectorLabels.server" . | nindent 4 }}