apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parca.fullname" . }}-server-config
  labels:
    {{- include "parca.labels.server" . | nindent 4 }}
data:
  parca.yaml: |-
    "debug_info":
      "bucket":
        "config":
          "directory": "./tmp"
        "type": "FILESYSTEM"
      "cache":
        "config":
          "directory": "./tmp"
        "type": "FILESYSTEM"