# ref: https://hub.docker.com/r/rlex/prometheus-webhook-dingtalk/
image: timonwong/prometheus-webhook-dingtalk
imageTag: v1.4.0

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 500m

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  # Security context settings
  runAsUser: 1000
  fsGroup: 1000
prometheus_webhook_dingtalk:
  serviceType: ClusterIP
  loadBalancerIP:
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster
  service:
    annotations: {}
  config:
#    block:
#      targets:
#        webhook1:
#          url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
  templates:
    custom: |
      {{ define "__text_alert_list" }}{{ range . }}
      **Time:** {{ .StartsAt | date "2006.01.02 15:04:05" }}
      **Labels**
      {{ range .Labels.SortedPairs }}> - {{ .Name }}: {{ .Value | markdown | html }}
      {{ end }}
      **Annotations**
      {{ range .Annotations.SortedPairs }}> - {{ .Name }}: {{ .Value | markdown | html }}
      {{ end }}
      **Source:** [{{ .GeneratorURL }}]({{ .GeneratorURL }})
      {{ end }}{{ end }}

## Additional prometheus-webhook-dingtalk container environment variables
extraEnv: {}
podAnnotations: {}
deploymentAnnotations: {}
