apiVersion: v1
kind: Service
metadata:
  name: {{ include "grist.fullname" . }}
  labels:
    {{- include "grist.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8484
      protocol: TCP
      name: http
  selector:
    {{- include "grist.selectorLabels" . | nindent 4 }}
