{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hcloud-fip-controller.serviceAccountName" . }}
  labels:
{{ include "hcloud-fip-controller.labels" . | nindent 4 }}
{{- end -}}
