apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  name: {{ .Release.Name }}-templates
#{ include "prometheus-webhook-dingtalk.namespace" . | indent 2 }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.prometheus_webhook_dingtalk.templates }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end -}}