apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  name: {{ .Release.Name }}-config
#{ include "prometheus-webhook-dingtalk.namespace" . | indent 2 }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.prometheus_webhook_dingtalk.config }}
  config.yml: |
{{ toYaml $value | default "{}" | indent 4 }}
{{- end -}}