apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus-webhook-dingtalk.fullname" . }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
    {{- range $key, $value := .Values.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app: {{ template "prometheus-webhook-dingtalk.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: {{ template "prometheus-webhook-dingtalk.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "prometheus-webhook-dingtalk.fullname" . }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: {{ template "prometheus-webhook-dingtalk.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- range $key, $value := .Values.extraEnv }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        ports:
        - name: web
          protocol: TCP
          containerPort: 8060
        volumeMounts:
        - name: configmap-config
          mountPath: /etc/prometheus-webhook-dingtalk
        - name: configmap-templates
          mountPath: /etc/prometheus-webhook-dingtalk/templates
      volumes:
      - name: configmap-config
        configMap:
          name: {{ .Release.Name }}-config
      - name: configmap-templates
        configMap:
          name: {{ .Release.Name }}-templates
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}